name: E2E

on:
  pull_request:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  PERCY_POSTINSTALL_BROWSER: true

jobs:
  percy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '18.17.1'
          cache: 'yarn'

      - name: Install Dependencies 📦
        run: yarn install --immutable

      - name: Sleep
        run: sleep 60

      - name: Wait for Vercel Preview
        uses: patrickedqvist/wait-for-vercel-preview@main
        id: vercel-preview
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          max_timeout: 200
          check_interval: 5

      - name: Run Percy
        run: yarn test
        working-directory: website
        env:
          TARGET_URL: ${{ steps.vercel-preview.outputs.url }}
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
